language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - android-25
    - build-tools-26.0.2
    - extra-android-m2repository

env:
  global:
    - secure: UYelHBhXRbRhr7pLx7pmIDX8ZnYfEJapJKScydj2xCGRHOX2/gqLdo181zTCpq4Q0uX32PO7Wjqi4foLVfawhFEHPAhZlvAvvkj5a3kldTRGGrNC0NzJLLr9Lfj/CIctahhzE4sTaYwNBUjDDs8MWaYIxJdcb7ymBXYKoQA06xhDIBYELTxDWTjxPbFQByp/tT6v9S/zlhgzQUL9+ygC6HaKrP+djRcfM+y6hFHOKZy25sT3MKhQMDNHlS7tXhN05o15Vk8C8CxMOpoUGF/vDdyKTraPAPPvBF9zgOiudra6C4LGHFYnkTjHMx636cKDe1TMT5jepGkLdFxLg3+gLph7Lx4iRGgcMw9AYAPkB4gjzxIa5yzXmO6oOwraU+o51OwSC6Bianf8vVPNeTkdcZtluXjL9MH+YD1TpwYFmTjIRjLSSgiwBYbWMRYgWeP6PGeenI7VZioAqJFWMdgO3C0ONUQOQExZW/iwJbKRddvZzblukQdRupJu01kq5kbGGFEPwqrGKtSggVykYjS9uCwRlLaPHpqWTcA51ZJgKx35K+/VwDMsa6age1vqIPZfbGhlVZJCaBmQICgsEyDuxPnH+JOmlcX1WOcoZy51HLFl3hOmblqg9KjFAWP2T8TXis4f+FXpP+BWhi3aepgfsFodXu2UjAckzUZUaLO/SHI=
    - secure: OwjPskHFIJdg2wv9+uz8hOrqpaqoU1AtCwaQmZFiOCB635qp4l9X4EjFndaCaGduC50KwkeDkFZ0eqnweFeL1KS3Tb8qFMpRcyV+iS2PfUTwA791x9bWQE9lip3sDcqiLUy2+6egmyj4pYX0eRL3svLd+LhIso4wzV/wka2ywjhmEqAJU20Qgm+lIaE9ypUVNNIU41yZ7GS27YmvybVCr3AKrgMYkTVEMhLLe5fS6OUuvpg2y6h965KKbKR+cKIbalJLjZYIyfjnaneIFsbYT72ERvHPSXEdDE6+AK5M32q966zPXf15qgaTAehWdD+jy/H0YwMBgfM60zT109eqTqZJCvi7HqEG07pDRFajTR7md81GVe6RsqFBusciJfGNvMxYn1B1rNXVXZKxUitjDW7HSAVqdem9kIJh8ncN5s9jCiaUJ3lhn+N7OEiZ7Wr4xkjwyTNJhMJNXZONbZlgEVX46IOx5syTd4nKtbif8fdt6TF7H8g52f+Zi29nWWPS4wRb1/CuZO8cvCBhBnTJ/9SoxOrReqnYMsWT315GUFzT44RJVsEHwQnOeOpYYt5iN9bPHJaBJgNZpRC4fotsMoG9DvSeOGe6ODWagy7ZnaolF3q9ChyQ+L+fo8WyS75xOJMRyQF4IpBMwuDGZ/EQdBF5HqaZysVclicjT9DP1Ic=

branches:
  only:
    - staging
    - trying
    - master

script: ./gradlew build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
