language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-23.0.2
    - extra-android-m2repository

branches:
  only:
    - staging
    - trying
    - master

script: ./gradlew assembleDebug

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
